# Generated by Django 5.0.6 on 2024-08-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
